Traceback (most recent call last):
  File "/home/brittny/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/brittny/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/brittny/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/brittny/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/brittny/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/brittny/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# To plot the entire dataset, we will plot each geographical location from the data
# on a world map. 

# Initial world map
world_map_all = folium.Map(location=[20,0], tiles='cartodbpositron', zoom_start=2)

# Looping over all the individuals' coordinates
for lat, lon in zip(data['latitude'], data['longitude']):
    folium.CircleMarker([lat, lon], radius=1, color='blue', fill=True, fill_color='blue').add_to(world_map_all)

world_map_all
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[13], line 5[0m
[1;32m      1[0m [38;5;66;03m# To plot the entire dataset, we will plot each geographical location from the data[39;00m
[1;32m      2[0m [38;5;66;03m# on a world map. [39;00m
[1;32m      3[0m 
[1;32m      4[0m [38;5;66;03m# Initial world map[39;00m
[0;32m----> 5[0m world_map_all [38;5;241m=[39m [43mfolium[49m[38;5;241m.[39mMap(location[38;5;241m=[39m[[38;5;241m20[39m,[38;5;241m0[39m], tiles[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcartodbpositron[39m[38;5;124m'[39m, zoom_start[38;5;241m=[39m[38;5;241m2[39m)
[1;32m      7[0m [38;5;66;03m# Looping over all the individuals' coordinates[39;00m
[1;32m      8[0m [38;5;28;01mfor[39;00m lat, lon [38;5;129;01min[39;00m [38;5;28mzip[39m(data[[38;5;124m'[39m[38;5;124mlatitude[39m[38;5;124m'[39m], data[[38;5;124m'[39m[38;5;124mlongitude[39m[38;5;124m'[39m]):

[0;31mNameError[0m: name 'folium' is not defined

